### ISSUE TITLE
можно пример прохождения формы на selenium

### ISSUE THREAD

**Issue by kirill-kirill-kirillov** [alexsok-bit/selenium_helper#1]
Можно хоть какой-то пример кода, как пройти hcaptcha с помощью данного расширения и полученного токена от сервисов? Это просто ужас какой-то, я бьюсь 3-й день...

**Comment by kirill-kirill-kirillov** [comment]
@alexsok-bit

**Comment by alexsok-bit** [comment]
вот тут есть пример https://github.com/2captcha/2captcha-python
а данное расширение нужно чтобы прокси поставить и обойти новый механизм защиты.

**Comment by kirill-kirill-kirillov** [comment]
> вот тут есть пример https://github.com/2captcha/2captcha-python
> а данное расширение нужно чтобы прокси поставить и обойти новый механизм защиты.

Это не "пример прохождения капчи с данным расширением", вы сослались на пример получения токена от сервиса, это и так хорошо задокументировано.

Каким-то чудом получилось вывести callback функцию после инъекции. Но после ее вызова - происходит перезагрузка страницы, можно пример вызова колбек функци с driver.execute_script?

**Comment by kirill-kirill-kirillov** [comment]
`driver.execute_script(f"window[widgetInfo['callback']]('{hcaptcha}');")`

Не отрабатывает

**Comment by alexsok-bit** [comment]
потому что ты не дочитал "и так хорошо описанную документацию"

```
function insert_token(token) {
    let iframes = document.getElementsByTagName("iframe");
    iframes[0].setAttribute("data-hcaptcha-response", token);
    let salt = iframes[0].getAttribute("data-hcaptcha-widget-id");
    document.getElementById("h-captcha-response-" + salt).innerHTML = token;
}


function submit_captcha(token) {
    // объект widgetInfo добавляется на страницу дополнением selenium_helper-0.1.6-fx.xpi
    // https://rucaptcha.com/blog/hcaptcha-cloudflare-ru
    window[widgetInfo.callback](token);
}
```

**Comment by kirill-kirill-kirillov** [comment]
<img width="1269" alt="Снимок экрана 2021-12-16 в 09 39 39" src="https://user-images.githubusercontent.com/88981796/146328509-1afe4a68-7a47-47a3-97e6-1988b00d7fd9.png">

Данный код приводит к перезагрузке страницы, как видно из консоли - запрос оказывается неуспешным.

**Comment by alexsok-bit** [comment]
надо смотреть логику авторизации на дискорде. потому что там капча как-то отдельно решается. и требуется для формы. тут, наверное, не нужно вызывать коллбек. или нужно, но уже не hcaptcha.

**Comment by kirill-kirill-kirillov** [comment]
> надо смотреть логику авторизации на дискорде. потому что там капча как-то отдельно решается. и требуется для формы. тут, наверное, не нужно вызывать коллбек. или нужно, но уже не hcaptcha.

Отличное расширение, на каком сайте оно вообще работает? На твоем тестовом?

**Comment by alexsok-bit** [comment]
на любом. но к сожалению мозгов оно не заменит
